### ISSUE TITLE
`TypeError: Cannot read property 'apikey' of undefined`

### ISSUE THREAD

**Issue by spikeekips** [codenamu/official-assets-explorer#144]
```
var sendgrid = require('sendgrid')(config.sendgrid.apikey)
                                                  ^

TypeError: Cannot read property 'apikey' of undefined
    at Object.<anonymous> (/usr/src/app/app/controllers/api/email.js:3:51)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/app/controllers/api/index.js:8:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/src/app/app/controllers/home.js:3:11)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at /usr/src/app/config/express.js:42:5
```

**Comment by spikeekips** [comment]
마지막 커밋 fc03f6dded49a7d3c2f86948f76d6d0d332fc949 에서 나온 에러입니다.

**Comment by spikeekips** [comment]
`sendgrid` 관련 설정을 포함시켜서 처리했어요.
